name: Built_To_Docker
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  #schedule:
  #  - cron: '30 * * * *'
jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DockerHub_ID }}
          password: ${{ secrets.DockerHub_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: virola/js_panel:latest
      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0

